---
- name: Copy the filterAAAA file
  copy:
    src: "files/filterAAAA.lua"
    dest: "/etc/{{ pdnsdir }}/filterAAAA.lua"
    owner: "{{ pdnsuser }}"
    group: "{{ pdnsuser }}"
    mode: "0444"

# - name: Copy the recursor file
#   copy:
#     src: "files/recursor.conf"
#     dest: "/etc/{{ pdnsdir }}/recursor.conf"
#     owner: "{{ pdnsuser }}"
#     group: "{{ pdnsuser }}"
#     mode: "0666"
#   # when: not wireguard

- name: Copy the recursor file for wireguard
  copy:
    src: "files/recursor_wireguard.conf"
    dest: "/etc/{{ pdnsdir }}/recursor.conf"
    owner: "{{ pdnsuser }}"
    group: "{{ pdnsuser }}"
    mode: '0666'
#   when: wireguard

- name: Copy zonefile
  template:
    src: zonefile-ins.{{ env }}.j2
    dest: "/etc/{{ pdnsdir }}/zonefile"
    owner: "{{ pdnsuser }}"
    group: "{{ pdnsuser }}"
    mode: "0644"
  notify: block_for_new_nodes

- meta: flush_handlers

# - name: Copy the resolv.conf to tmp
#   template:
#     src: "configs/{{ env }}/resolv.conf.j2"
#     dest: "/tmp/resolv.conf"
#     owner: root
#     group: root
#     mode: "0444"

# - name: Add IP address of all hosts to all hosts
#   lineinfile:
#     path: /tmp/resolv.conf
#     regexp: ".*{{ item }}$"
#     line: "nameserver {{ item }}"
#     state: present
#     insertbefore: BOF
#   with_items: "{{ dns_hosts }}"

# - name: Copy resolv.conf from tmp to etc
#   copy:
#     src: "/tmp/resolv.conf"
#     dest: "/etc/resolv.conf"
#     remote_src: true
#     owner: root
#     group: root
#     mode: "0444"

# - name: Remove dnsmasq package
#   apt:
#     name: dnsmasq
#     state: absent

# - name: Stop systemd-resolved and disable it
#   service:
#     name: systemd-resolved
#     enabled: no
#     state: stopped

# - name: Start service pdns-recursor, if not started
#   service:
#     name: pdns-recursor
#     state: restarted
#   register: pdns_state

# - name: Copy the resolv.conf to etc
#   template:
#     src: "resolv.conf.j2"
#     dest: "/etc/resolv.conf"
#     owner: root
#     group: root
#     mode: "0444"
#   when: pdns_state is succeeded




