---
- name: Copy the resolv.conf to tmp
  template:
    src: "configs/{{ env }}/resolv.conf.j2"
    dest: "/tmp/resolv.conf"
    owner: root
    group: root
    mode: "0444"

- name: Add IP address of all hosts to all hosts
  lineinfile:
    path: /tmp/resolv.conf
    regexp: ".*{{ item }}$"
    line: "nameserver {{ item }}"
    state: present
    insertbefore: BOF
  with_items: "{{ dns_hosts }}"

- name: Copy resolv.conf from tmp to etc
  copy:
    src: "/tmp/resolv.conf"
    dest: "/etc/resolv.conf"
    remote_src: true
    owner: root
    group: root
    mode: "0444"

- name: Remove dnsmasq package
  apt:
    name: dnsmasq
    state: absent

- name: Stop systemd-resolved and disable it
  service:
    name: systemd-resolved
    enabled: no
    state: stopped

- name: Start service pdns-recursor, if not started
  service:
    name: pdns-recursor
    state: restarted
  register: pdns_state

- name: Copy the resolv.conf to etc
  template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    mode: "0444"
  when: pdns_state is succeeded

- name: Check if fqdn is resolvable after starting pdns
  ansible.builtin.command: hostname -f
  register: fqdn
  ignore_errors: true

- name:
  block:
    - name: wait for 60 sec to restart pdns
      wait_for:
        timeout: 60 

    - name: restart pdns-recursor
      service:
        name: pdns-recursor
        state: restarted
  when: fqdn is failed
