[http.middlewares.simpleAuth.basicAuth]
  users = [
    "risheeth:$apr1$PL//SvsQ$duEjj6LEYseVrlNLzDWx0."
  ]

[http.routers.api]
  rule = "Host(`192.168.1.53`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"