---
# Handlers for Aerospike
- name: restart aerospike
  service: name=aerospike state=restarted

- name: start aerospike
  service: name=aerospike state=started

- name: stop aerospike
  service: name=aerospike state=stopped