---
- name: install_xfsprogs_if_not_there
  become: yes
  package:
    name:
      - xfsprogs
      - lvm2
    state: present

- name: enabling and starting lvmetad
  service:
    name: "{{ item }}"
    state: "started"
    enabled: yes
  become: true
  loop:
    - "lvm2-lvmetad.service"
    - "lvm2-lvmetad.socket"
  when: ansible_distribution_version  <  "20.04" 

- name: remove existing partitions
  become: yes
  lvol:
    vg: vg_as
    lv: lv_free
    state: absent
    pvs: "{{ add_disk_name }}"
    force: yes


- name: create a volume group on top of {{ add_disk_name }}
  become: yes
  lvg:
    vg: vg_as
    pvs: "{{ add_disk_name }}"

- name: create lv partitions
  become: yes
  lvol:
    vg: vg_as
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
    pvs: "{{ add_disk_name }}"
    shrink: no
  with_items:
    - name: lv_aerospike
      size: "{{ lvextend_percentage }}%FREE"
- name: Create a xfs filesystem on lvm "/dev/mapper/".
  become: yes
  filesystem:
    fstype: xfs
    dev: "/dev/mapper/vg_as-{{ item }}"
    force: no
  with_items:
    - lv_aerospike

- name: Create a directory to mount the filesystem.
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - /var/lib/aerospike

- name: Mount and bind a volume
  become: yes
  mount:
    src: "/dev/vg_as/{{ item.src }}"
    path: "{{ item.path }}"
    state: mounted
    fstype: xfs
  with_items:
    - { src: lv_aerospike, path: /var/lib/aerospike }
