---
# - name: Run a script using an executable in a system path
#   #script: scripts/install_E{{aerospike_version}}.sh
#   script: scripts/install_E4.8.0.6.sh
#   args:
#     executable: /bin/bash

- name: Create Aerospike ssl certs directory.
  file:
    path: "{{ aerospike_ssl_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Check whether download exists
  stat:
    path: "{{ download_path }}"
  register: stat_download_path

- name: Download Aerospike Cor link{{ 'Enterprise' if enterprise else 'Community' }}, version = {{ aerospike_version }} {{ aerospike_distribution }} if not already downloaded
  get_url:
    url: "{{ cor_download_url }}"
    dest: "/home/azureuser"

- name: Install a Aerospike-server.deb package
  apt:
    deb: /home/azureuser/aerospike-server-enterprise-4.9.0.27-8.ubuntu20.04.x86_64.deb    

# - name: Unpack and Install Aerospike
#   dpkg_selections:
#     name: "aerospike-server-enterprise-4.9.0.27-8.ubuntu20.04.x86_64.deb"
#     selection: install

- name: Download Aerospike Tools
  get_url:
    url: "http://cor-mirror101.phonepe.nb1/aerospike-tools-4.0.4.ubuntu20.04.x86_64.deb"
    dest: "/home/azureuser"

- name: Install a .deb package
  apt:
    deb: /home/azureuser/aerospike-tools-4.0.4.ubuntu20.04.x86_64.deb   

# - name: Unpack and Install Aerospike Tools
#   dpkg_selections:
#     name: "aerospike-tools-4.0.4.ubuntu20.04.x86_64.deb"
#     selection: install

- name: Download Aerospike-AMC
  get_url:
    url: "{{ cor_amc_download_url }}"
    dest: "/home/azureuser"

- name: Install a .deb package
  apt:
    deb: /home/azureuser/aerospike-amc-e4.0.24.deb


# - name: Unpack and Install Aerospike-AMC
#   dpkg_selections:
#     name: "aerospike-amc-e4.0.24.deb"
#     selection: install