---

# - name: Install libcurl (required for 5.1+)
#   apt:
#     name: libcurl3
#     state: present


- name: Create Aerospike download directory.
  file:
    path: "{{ aerospike_source_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create Aerospike ssl certs directory.
  file:
    path: "{{ aerospike_ssl_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755


- name: Check whether download exists
  stat:
    path: "{{ download_path }}"
  register: stat_download_path

- name: Download Aerospike {{ 'Enterprise' if enterprise else 'Community' }}, version = {{ aerospike_version }}, distribution = {{ aerospike_distribution }} if not already downloaded
  get_url:
    url: "{{ download_url }}"
    dest: "{{ download_path }}"
  when: not stat_download_path.stat.exists 


- name: Unpack installer
  unarchive:
    remote_src: "yes"
    src: "{{ download_path }}"
    dest: "{{ download_file_dir }}"
    list_files: true
  register: result

- name: Get install directory
  set_fact:
    install_directory: "{{ result.files[0] }}"

- name: "Install Aerospike with tls = {{ tls_enabled }}, encryption at rest = {{ encryption_at_rest }}"
  command:
    chdir: "{{ download_file_dir }}/{{ install_directory }}"
    cmd: "{{ download_file_dir }}/{{ install_directory }}/asinstall"
