# ansible_azure_rm.yml - Needs to end with azurerm
# Required for all azure_rm inventory plugin configs
plugin: azure_rm
# Forces to use cli with auth session instead of teh automatic auth source when listed as cli
# Change to auto on demand
auth_source: auto
# Fetches vms from the said resource groups
include_vm_resource_groups:
  - 'ppe_stg_internship'
# Fetches vms from vmss in all resource groups
#include_vmss_resource_groups:
#  - '*'
# places hosts in dynamically-created groups based on a variable value.
keyed_groups:
  - prefix: tag
    key: tags
# excludes a host from the inventory when any of these expressions is true, can refer to any vars defined on the host
#exclude_host_filters:
# excludes hosts that are powered off
#  - powerstate != 'running'
#  - provisioning_state != 'succeeded'
