# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      dhcp4: no
      dhcp6: no
      addresses: [172.10.0.13/30]
    enp0s8:
      dhcp4: no
      dhcp6: no
      addresses: [172.10.0.1/30] 
    enp0s9:
      dhcp4: no
      dhcp6: no
      addresses: [172.10.0.5/30]
    enp0s10:
      dhcp4: no
      dhcp6: no
      addresses: [172.10.0.9/30]
    lo:
      addresses: [10.1.1.1/32]	   
  version: 2