- name: set timezone to "{{ timezone }}"
  timezone:
    name: "{{ timezone }}"

- name: Install chrony
  apt:
    name: chrony
    state: present

- name: Remove ntp if present
  apt:
    name: ntp
    state: absent

# - name: Apparmor related cleanup for ntp
#   file:
#     src: /etc/apparmor.d/usr.sbin.ntpd
#     dest: /etc/apparmor.d/disable/usr.sbin.ntpd
#     state: link

# # - name: Apparmor related cleanup for ntp
# #   command: ln -s /etc/apparmor.d/usr.sbin.ntpd /etc/apparmor.d/disable/

# - name: Apparmor related cleanup for ntp
#   command: apparmor_parser -R /etc/apparmor.d/usr.sbin.ntpd

- name: Copy chrony configuration
  template:
    src: etc/chrony/chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: _chrony
    group: _chrony
    mode: 0644
  notify: Enable chrony service
    
    #
# - name: Enable chrony service
#   service: 
#     name: chrony
#     enabled: yes
#     state: restarted

- meta: flush_handlers
#- include_tasks: monitoring.yml