---

- hosts: group
  become: yes
  vars: 
    mysql_root_password: '948164'
  tasks:
  - name: update mysql root password for all root accounts 
    mysql_user:  
      name: root  
      host: group
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"  
  - name: create databse Nginx and dump file
    mysql_db: name=Nginx state=present login_user=root login_password="{{ mysql_root_password }}"
  - name: insert sql file into database
    mysql_db: name=Nginx state=import target=/home/risheeth/ngnix_access_log.sql login_user=root login_password="{{ mysql_root_password }}"

