---
# - name: check if disk exist
#   shell: ls /dev/sd*
#   register: dist_status

# - include_tasks: disk_partitioning.yml
#   when: add_disk_name in dist_status.stdout

- name: Run when data disk is present
  block:
    - name: find the disks with partitions
      shell: lsblk -ln -o NAME,TYPE | grep disk | awk '{print $1}' | xargs -i bash -c "ls /dev/ | grep {} | grep -E {}[0-9] | sed 's/[0-9]//g'" | uniq
      args:
        executable: /bin/bash
      register: cmd1
      ignore_errors: yes

    - name: find all disks
      shell: lsblk -ln -o NAME,TYPE | grep disk | awk '{print $1}'
      args:
        executable: /bin/bash
      register: cmd2
      ignore_errors: yes

    - name: find the new disk
      set_fact:
        difference: "{{ (cmd2.stdout_lines | difference(cmd1.stdout_lines)) | first }}"

    - name: set the new disk path
      set_fact:
        add_disk_name: "/dev/{{ difference }}"

    - name: check pvdisplay
      shell: pvdisplay
      register: pvdisplay_output
    
    - include_tasks: disk_partitioning.yml
      when: pvdisplay_output.stdout == ""

  when: 'is_data_disk_present == "true"'

- include_tasks: repository.yml

- include_tasks: install.yml

- include_tasks: config.yml

- include_tasks: cluster.yml
  when: rabbitmq_create_cluster == "true"

- include_tasks: plugin.yml

- include_tasks: create_user.yml
