---
- name: Copy rabbitmq_delayed_message_exchange plugin
  copy:
    src: files/rabbitmq_delayed_message_exchange-3.8.9.ez
    dest: /usr/lib/rabbitmq/lib/rabbitmq_server-3.8.9/plugins/rabbitmq_delayed_message_exchange-3.8.9.ez
    owner: rabbitmq
    group: rabbitmq
    mode: '0644'

- name: Enable the plugins and restart rabbitmq-server
  rabbitmq_plugin:
    names: "{{ item }}"
    state: enabled
    new_only: yes
  with_items: "{{ rabbitmq_plugins }}"
