---
# Setup installation repositories
# Standart repository for Debian / Ubuntu (https://www.rabbitmq.com/install-debian.html)
#- name: Add RabbitMQ repository to sources
#  template:
#    src: etc/apt/sources.list.d/rabbitmq.list.j2
#    dest: /etc/apt/sources.list.d/rabbitmq.list
#    owner: root
#    group: root
#    mode: '0644'

- name: Add login.defs
  copy:
    src: files/login.defs
    dest: /etc/login.defs
    owner: root
    group: root
    mode: '0644'

- name: import key(erl)
  apt_key:
    url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    state: present

- name: Add erlang version 
  template:
    src: etc/apt/sources.list.d/erlang.ver.j2
    dest: /etc/apt/preferences.d/erlang
    owner: root
    group: root
    mode: '0644'

- name: Add erlang repository to sources
  template:
    src: etc/apt/sources.list.d/erlang.repo.j2
    dest: /etc/apt/sources.list.d/rabbitmq.list
    owner: root
    group: root
    mode: '0644'

#- name: Add RabbitMQ main server apt key
#  apt_key:
#    keyserver: hkps://keys.openpgp.org
#    id: '0x0A9AF2115F4687BD29803A206B73A36E6026DFCA'

- name: Download Rmq
  get_url:
    url: "http://cor-mirror101.phonepe.nb1/rabbitmq-server_3.8.9-1_all.deb"
    dest: "/home/azureuser"



#- name: Add RabbitMQ signing key
#  apt_key:
#    url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
#    state: present

- name: Ensure the locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present

# - name: Get current locale 
#   command: locale
#   register: locale_status
#   changed_when: false

# - name: Parse 'LANG' from current locale and language configuration{{ locale_status }}
#   set_fact:
#     sys_locale: "{{ (locale_status.stdout | regex_search('LC_ALL=([^\n]+)', '\\1') | first).description }}"

- name: set as default locale"{{ sys_locale }}""{{ locale_lc_all }}"
  command: update-locale LC_ALL="{{ locale_lc_all }}"
# changed_when: locale_lc_all != sys_locale


  