[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$wbnPs3Kb$h1BiBUGkHUWsNWf0u4Wh2."
  ]

[http.routers.api]
  rule = "Host(`192.168.0.107`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"