# Downloading 
aerospike_download_suffix: "/artifact"

aerospike_download_prefix: "http://www.aerospike.com/{{ 'enterprise/' if enterprise else ''}}download/server"
aerospike_edition: "{{ 'ee' if enterprise else 'ce' }}"

download_url: "{{ aerospike_download_prefix }}/{{ aerospike_version }}{{ aerospike_download_suffix }}/{{ aerospike_distribution }}"
download_file_name: "aerospike-{{ aerospike_edition }}-{{ aerospike_distribution }}-{{ aerospike_version }}.tar"
download_file_dir: "{{ temp_directory }}"
download_path: "{{ download_file_dir }}/{{ download_file_name }}"

cor_download_file_name: "aerospike-{{ aerospike_edition }}-{{ aerospike_distribution }}-{{ aerospike_version }}.deb"
cor_download_path: "{{ download_file_dir }}/{{ cor_download_file_name }}"
cor_download_url: "http://cor-mirror101.phonepe.nb1/aerospike-server-enterprise-{{ aerospike_version }}-8.{{ aerospike_distribution }}.x86_64.deb"

cor_amc_download_file_name: "aerospike-amc-e4.0.24.deb"
cor_amc_download_path: "{{ download_file_dir }}/{{ cor-amc_download_file_name }}"
cor_amc_download_url: "http://cor-mirror101.phonepe.nb1/aerospike-amc-e4.0.24.deb"
# Feature key
default_feature_key_path: "features.conf"
feature_key_path: "{{ feature_key if feature_key is defined else default_feature_key_path }}"

# Encryption
encryption_key_file_path: "/etc/aerospike/encryption-at-rest-key.dat"

# Names of files generated/used by the playbooks - leave as is
# =======================================================
aerospike_conf_file: "etc/aerospike/aerospike.conf"
# TLS
tls_name: "phonepeaerospike"
certificates_directory: /etc/aerospike/ssl

# Ports
service_port: 3000
tls_service_port: 4333
heartbeat_port: 3002
fabric_port: 3001
tls_fabric_port: 3011
info_port: 3003


# Other
temp_directory: "/tmp"
#nodes: tag_service_aerospike

