---
# Handlers for RabbitMQ
- name: restart rabbitmq-server
  service: name=rabbitmq-server state=restarted

- name: start rabbitmq-server
  service: name=rabbitmq-server state=started

- name: stop rabbitmq-server
  service: name=rabbitmq-server state=stopped

- name: failed node restart
  service: name=rabbitmq-server state=restarted
  ignore_errors: yes

- name: change cluster_size
  set_fact:
    nodes_in_cluster : "0"