---
- name: Add salt apt key
  apt_key:
    url: https://repo.saltstack.com/py3/ubuntu/{{ ansible_distribution_version }}/amd64/{{ salt_version }}/SALTSTACK-GPG-KEY.pub
    state: present

- name: Copy the repo file
  template:
    src: "saltstack.list.j2"
    dest: /etc/apt/sources.list.d/saltstack.list
    owner: root
    group: root
    mode: '0644'

- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Install salt-minion
  apt:
    name: salt-minion
    state: present
