---
- name: Add cor-mirror apt key nm5
  apt_key:
    url: http://{{ mirror_link }}/{{ key_path }}
    state: present
  retries: 2
  register: stat
  delay: 5
  until: stat is not failed
 
#have to move this to a variable
# - name: Show the name of master nodeprint
#   debug:
#     msg: "{{ qw }}"

- name: Add sources.list
  template:
    src: "apt_mirror.list.j2"
    dest: "/etc/apt/sources.list"

- name: Add tinyproxy to apt conf
  template:
    src: "apt.conf.j2"
    dest: "/etc/apt/apt.conf"

- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
